services:
  - type: web
    name: college-chatbot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
    disk:
      name: nltk-cache
      mountPath: /opt/render/project/src/nltk_data

